<?php

namespace Saccharine\BpmnEngine\Policies;

use Saccharine\BpmnEngine\Models\WorkflowInstance;
use Saccharine\BpmnEngine\Enums\WorkflowPermission;

class WorkflowInstancePolicy
{
    public function viewAny($user): bool {
        return $user->can(WorkflowPermission::VIEW->value);
    }

    public function view($user, WorkflowInstance $model): bool {
        return $user->can(WorkflowPermission::VIEW->value);
    }

    // Instances are generated by the engine, so users shouldn't create them manually via UI
    public function create($user): bool {
        return false;
    } 

    public function update($user, WorkflowInstance $model): bool {
        return false;
    }

    public function delete($user, WorkflowInstance $model): bool {
        return false;
    }

}